# Generated by Django 4.1.7 on 2023-03-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HumidityTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temprature', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('rectime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'HumidityTemp',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.TextField(max_length=14)),
                ('user_password', models.TextField(max_length=30)),
            ],
            options={
                'db_table': 'UserDetail',
            },
        ),
    ]
