# Generated by Django 4.1.7 on 2023-03-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thefarm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.TextField(max_length=14)),
                ('user_password', models.TextField(max_length=30)),
            ],
        ),
    ]
